-- AlterTable
ALTER TABLE `Settings`
  ADD COLUMN `plan` VARCHAR(191) NOT NULL DEFAULT 'free',
  ADD COLUMN `subscriptionId` VARCHAR(191) NULL,
  ADD COLUMN `monthlyOrderCount` INT NOT NULL DEFAULT 0,
  ADD COLUMN `orderCountResetDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
